const express = require("express");
const router = express.Router();
const data = [
  {
    id: 100001,
    name: "قسم ملابس الرجال ",
    products: [
      {
        id: 1,
        name: "عرض طقم كلاسيك ( بنطلون + قميص ) ",
        description: [
          "ترنج شورت شطرنج",
          "-خامة ميلتون ليكرا",
          "-طباعه سبليمشن",
          "-تقفيل وفينش محترم",
          "-مقاسات (L-XL-XXL)",
          "-الوان(اسود-ابيض-موف-كشمير)",
          "جدول التلبيس",
          "من 50 كيلو ل 70 كيلو مقاس لارج",
          "من 70 كيلو ل 80 كيلو مقاس اكس لارج",
          "من 80 كيلو ل 100كيلو مقاس اتنين اكس",
        ],
        size: [
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
        ],
        colors: [
          "أحمر",
          "أبيض",
          "أسود",
          "أصفر",
          "أحمر",
          "أبيض",
          "أسود",
          "أصفر",
          "أحمر",
          "أبيض",
          "موف",
          "اخضر",
        ],
        available: [
          "متوفر",
          "غير متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "غير متوفر",
        ],

        isAvailable: false,
        image:
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688511611/Jammal/MEN/IMG_5610_tu6f1p.jpg",
        editedImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688511611/Jammal/MEN/IMG_5610_tu6f1p.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515763/Jammal/MEN/Product/IMG_5616_rscshw.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515765/Jammal/MEN/Product/IMG_5615_m2llte.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515761/Jammal/MEN/Product/IMG_5614_hcaovw.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515761/Jammal/MEN/Product/IMG_5613_h8gsej.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515762/Jammal/MEN/Product/IMG_5612_dywjcs.jpg",
        ],
        normalImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
      },

      {
        id: 2,
        name: "بنطلون كلاسييك        ",
        description: [
          "ترنج شورت شطرنج",
          "-خامة ميلتون ليكرا",
          "-طباعه سبليمشن",
          "-تقفيل وفينش محترم",
          "-مقاسات (L-XL-XXL)",
          "-الوان(اسود-ابيض-موف-كشمير)",
          "جدول التلبيس",
          "من 50 كيلو ل 70 كيلو مقاس لارج",
          "من 70 كيلو ل 80 كيلو مقاس اكس لارج",
          "من 80 كيلو ل 100كيلو مقاس اتنين اكس",
        ],
        size: [
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
          "L",
          "XL",
          "XXL",
        ],
        colors: [
          "أحمر",
          "أبيض",
          "أسود",
          "أصفر",
          "أحمر",
          "أبيض",
          "أسود",
          "أصفر",
          "أحمر",
          "أبيض",
          "موف",
          "اخضر",
        ],
        available: [
          "متوفر",
          "غير متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "متوفر",
          "غير متوفر",
        ],

        isAvailable: false,
        image:
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688511611/Jammal/MEN/IMG_5610_tu6f1p.jpg",
        editedImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688511611/Jammal/MEN/IMG_5610_tu6f1p.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515763/Jammal/MEN/Product/IMG_5616_rscshw.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515765/Jammal/MEN/Product/IMG_5615_m2llte.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515761/Jammal/MEN/Product/IMG_5614_hcaovw.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515761/Jammal/MEN/Product/IMG_5613_h8gsej.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688515762/Jammal/MEN/Product/IMG_5612_dywjcs.jpg",
        ],
        normalImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
      },
    ],
  },
  {
    id: 100002,
    name: "قسم ملابس النساء",
    products: [
      {
        id: 101,
        name: "تيشرت أوفر سايز مخطط",
        description: [
          "تيشرت أوفر سايز مخط",
          " الخامه قطن إصبن",
          " الطول ٧٥سم المقاس وان سيز ل ٨٠ك",
        ],
        size: ["وان سيز", "وان سيز"],
        colors: ["أسود", "أسود"],
        available: ["متوفر", "متوفر"],

        isAvailable: true,
        image:
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483297/Jammal/Women/YQlA9bcdlpxi13ZLeOjbYq6HWXHuM6zbZw7qRTRe_eto815.jpg",
        editedImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483297/Jammal/Women/YQlA9bcdlpxi13ZLeOjbYq6HWXHuM6zbZw7qRTRe_eto815.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483297/Jammal/Women/YQlA9bcdlpxi13ZLeOjbYq6HWXHuM6zbZw7qRTRe_eto815.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
        normalImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
      },
      {
        id: 102,
        name: "جيبه zebra",
        description: [
          "جيبه zebra ",
          " الخامه اسكوبا كريب",
          " المقاس وان سيز ل ٨٠ك",
        ],
        size: ["وان سيز", "وان سيز"],
        colors: ["أسود", "أسود"],
        available: ["متوفر", "متوفر"],

        isAvailable: true,
        image:
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483304/Jammal/Women/xvGsR3GLoRrXhNeabjME6q8Za1XWTQHu6MXkssXO_zp3vvc.jpg",
        editedImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483304/Jammal/Women/xvGsR3GLoRrXhNeabjME6q8Za1XWTQHu6MXkssXO_zp3vvc.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688483304/Jammal/Women/xvGsR3GLoRrXhNeabjME6q8Za1XWTQHu6MXkssXO_zp3vvc.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
        normalImages: [
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
          "https://res.cloudinary.com/duc04fwdb/image/upload/v1688749538/Jammal/Holder/loading_fjikc2.jpg",
        ],
      },
    ],
  },
];

router.get("/data", (req, res) => {
  res.send(data);
});

module.exports = router;
